container:
  image: node:10

lint_task:
  install_script: npm install
  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:11
      image: node:10
      image: node:8
  install_script: npm install
  test_script: npm test

commit_lint_task:
  script:
    - npm install
    - npm run commitlint

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[a37de46f626239d325b37a87f6b3fcc77bdc6cf71935c172176d936ba53c9cfd1160e4350a1a6cf68ba6ade3ccea669f]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - test_task
    - lint_task
    - commit_lint_task
  environment:
    GITHUB_TOKEN: ENCRYPTED[fb6733c8f3f4fa77cbc4fcd387973afdefd1bf2f0fb9e957f9cc44dc73ec17f4bde2b4f338c81f6c4a66763010ccd987]
    NPM_TOKEN: ENCRYPTED[a2fe4db119016292b8bbd723c93789b358f98bc9fecfd322684723e3484b7e7d80e14456b46dda994a866c6c3beb0825]
  script:
    - npm install
    - npm run compile
    - npx semantic-release
