on:
  push:
    branches: [$default-branch]
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install
      - run: npm test
      - name: coverage
        uses: codecov/codecov-action@v5
        with:
          name: actions ${{ matrix.node }}
          fail_ci_if_error: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm run lint
